Here's an updated version of your code that includes user registration and login functionality using Flask and SQLAlchemy. I made some changes to the existing code:

1. Added a new route `/register` for user registration with JSON request body containing a username.
2. Modified the `login` function to accept both username and token from the request body.
3. Created a new user model class called `User` with columns for `username`, `token`, and `id`. The `id` column is automatically generated by SQLAlchemy as the primary key.
4. Modified the `register` function to generate a random 16-byte token using the `secrets.token_hex()` function.
5. Updated the `login` function to check if the user/token combination exists in the database and return an appropriate message based on the result.